# NumPy Operations

## Arithmetic

You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:

array와 array간 그리고 상수와 array간에는 산술연산이 가능합니다.

In [1]:
import numpy as np
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
#arr+arr는 같은 index를 가진 원소들을 더해줍니다.
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [7]:
#마찬가지로 같은 index의 원소들을 곱해줍니다.
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [9]:
#뻴셈도 가능합니다.
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
#파이썬에서는 기본적으로 0으로 나누는 것을 허용하지 않습니다.
1/0

ZeroDivisionError: division by zero

In [12]:
# Warning on division by zero, but not an error!
# Just replaced with nan
# array연산안에서 0으로 나눠질경우 파이썬은 에러를 내보내지 않고 경고를 내보냅니다.
# 0/0은 nan(null)로 리턴되고 나머지는 올바르게 연산됩니다.
arr/arr

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in true_divide
  """


array([ nan,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.])

In [13]:
# Also warning, but not an error instead infinity
# 1/0은 nan대신 inf(infinity)로 리턴됩니다.
1/arr

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([        inf,  1.        ,  0.5       ,  0.33333333,  0.25      ,
        0.2       ,  0.16666667,  0.14285714,  0.125     ,  0.11111111,
        0.1       ])

In [15]:
# **는 지수연산입니다.
# arr**3은 arr안에있는 각각의 원소를 모두 세제곱하게 됩니다
arr**3

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000], dtype=int32)

## Universal Array Functions

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

Numpy에는 산술연산 외에 다양한 수학적인 조작을 가능하게 해주는 함수들이 있습니다.

In [17]:
#Taking Square Roots
#각각의 원소에 루트를 씌운 결과를 리턴합니다.
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [18]:
#Calcualting exponential (e^)
#exponential 자연상수 연산도 가능합니다.
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [19]:
#최댓값을 알아낼 수 있습니다.
np.max(arr) #same as arr.max()

10

In [15]:
#모든 원소를 sin함수에 대입합니다.
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [24]:
#로그에 대입할 수 있습니다.
#다음은 자연로그를 이용한 것입니다.
np.log(arr)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in log
  This is separate from the ipykernel package so we can avoid doing imports until


array([       -inf,  0.        ,  0.69314718,  1.09861229,  1.38629436,
        1.60943791,  1.79175947,  1.94591015,  2.07944154,  2.19722458,
        2.30258509])

#### 참고

Universal function에 대한 더 자세한 설명은 docs.scipy.org/doc/numpy/reference/ufuncs.html 을 참고해주세요

# Great Job!

That's all we need to know for now!