### NumPy Matrices

In [1]:
import numpy

In [3]:
a = numpy.array([[1,2],[3,4]]) 

In [5]:
m = numpy.mat(a) # convert 2-d array to matrix 

In [6]:
m

matrix([[1, 2],
        [3, 4]])

In [8]:
m = numpy.matrix([[1, 2], [3, 4]]) 

In [9]:
m

matrix([[1, 2],
        [3, 4]])

In [10]:
a[0]

array([1, 2])

In [11]:
m[0]

matrix([[1, 2]])

In [12]:
a*a

array([[ 1,  4],
       [ 9, 16]])

In [13]:
m*m

matrix([[ 7, 10],
        [15, 22]])

In [14]:
a**3 

array([[ 1,  8],
       [27, 64]], dtype=int32)

In [15]:
m**3 

matrix([[ 37,  54],
        [ 81, 118]])

In [16]:
m.T

matrix([[1, 3],
        [2, 4]])

In [17]:
m.H

matrix([[1, 3],
        [2, 4]])

In [18]:
m.I

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

In [19]:
a = numpy.array([1,2,3], float) 

In [20]:
a

array([ 1.,  2.,  3.])

In [22]:
b = numpy.array([5,2,6], float) 

In [23]:
b

array([ 5.,  2.,  6.])

In [24]:
a + b 

array([ 6.,  4.,  9.])

In [26]:
a - b 

array([-4.,  0., -3.])

In [27]:
a * b 

array([  5.,   4.,  18.])

In [28]:
b / a 

array([ 5.,  1.,  2.])

In [29]:
a % b 

array([ 1.,  0.,  3.])

In [30]:
b**a 

array([   5.,    4.,  216.])

In [31]:
a = numpy.array([[1, 2], [3, 4], [5, 6]], float) 

In [32]:
b = numpy.array([-1, 3], float) 

In [33]:
a

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.]])

In [34]:
b

array([-1.,  3.])

In [35]:
a + b

array([[ 0.,  5.],
       [ 2.,  7.],
       [ 4.,  9.]])

In [36]:
a = numpy.array([[1, 2], [3, 4], [5, 6]], float) 

In [37]:
b = numpy.array([-1, 3], float) 

In [38]:
a * a

array([[  1.,   4.],
       [  9.,  16.],
       [ 25.,  36.]])

In [39]:
b * b

array([ 1.,  9.])

In [40]:
a * b

array([[ -1.,   6.],
       [ -3.,  12.],
       [ -5.,  18.]])

In [41]:
A = numpy.array([[n+m*10 for n in range(5)] for m in range(5)])

In [42]:
v1 = numpy.arange(0, 5)

In [43]:
A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [44]:
v1

array([0, 1, 2, 3, 4])

In [45]:
numpy.dot(A,A)

array([[ 300,  310,  320,  330,  340],
       [1300, 1360, 1420, 1480, 1540],
       [2300, 2410, 2520, 2630, 2740],
       [3300, 3460, 3620, 3780, 3940],
       [4300, 4510, 4720, 4930, 5140]])

In [46]:
numpy.dot(A,v1)

array([ 30, 130, 230, 330, 430])

In [47]:
numpy.dot(v1,v1)

30

In [48]:
M = numpy.matrix(A)

In [49]:
v = numpy.matrix(v1).T

In [50]:
v

matrix([[0],
        [1],
        [2],
        [3],
        [4]])

In [51]:
M*v

matrix([[ 30],
        [130],
        [230],
        [330],
        [430]])

In [52]:
v.T * v

matrix([[30]])

In [53]:
v + M*v

matrix([[ 30],
        [131],
        [232],
        [333],
        [434]])