In [1]:
import numpy 

In [2]:
a = numpy.array([[1.0, 2.0], [4.0, 3.0]]) 

In [4]:
 print (a)

[[ 1.  2.]
 [ 4.  3.]]


In [5]:
a.transpose() 

array([[ 1.,  4.],
       [ 2.,  3.]])

In [6]:
numpy.linalg.inv(a)

array([[-0.6,  0.4],
       [ 0.8, -0.2]])

In [7]:
u = numpy.eye(2) 

In [8]:
u

array([[ 1.,  0.],
       [ 0.,  1.]])

In [9]:
j = numpy.array([[0.0, -1.0], [1.0, 0.0]]) 

In [10]:
numpy.dot (j, j) 

array([[-1.,  0.],
       [ 0., -1.]])