In [1]:
import numpy as np

In [2]:
a = np.array([1, 4, 3, 8, 9, 2, 3], float) 

In [3]:
np.median(a)

3.0

In [4]:
a = np.array([[1, 2, 1, 3], [5, 3, 1, 8]], float) 

In [5]:
c = np.corrcoef(a) 

In [6]:
c

array([[ 1.        ,  0.72870505],
       [ 0.72870505,  1.        ]])

In [7]:
np.cov(a)

array([[ 0.91666667,  2.08333333],
       [ 2.08333333,  8.91666667]])

In [8]:
m = np.mat([[1,2],[3,4]]) 

In [9]:
a = np.array([[1,2],[3,4]]) 

In [10]:
a

array([[1, 2],
       [3, 4]])

In [11]:
m

matrix([[1, 2],
        [3, 4]])